### ISSUE TITLE
Does this addon still work?

### ISSUE THREAD

**Issue by bsebastian86** [cubeweb/acf-categories#11]
Does this addon still work? Doesn't seem to work with ACF Pro 5+

**Comment by cubeweb** [comment]
No I don't maintain the plugin any more since ACF has its own taxonomy field in v5

**Comment by bsebastian86** [comment]
Yeh, but ACF's taxonomy doesn't allow to filter based on parent or child_of. It displays all available taxonomy. Sucks, this would have been helpful. Thanks anyway.

**Comment by cubeweb** [comment]
Sorry, I have actually asked Elliot from ACF to include ACF Categories in the official add ons
but I had the response a gave you. If I find some free time I will make an update an let you know so you can test it.

**Comment by bsebastian86** [comment]
Shame. Would be awesome, but I might have a crack at it myself. Thanks again.
