### ISSUE TITLE
Conditional Logic

### ISSUE THREAD

**Issue by seganaUK** [cubeweb/acf-categories#4]
Hi,

Installed your plugin as its exactly what I need, however there is one issue / feature request.

I don't seem to be able to use a Category field with conditional logic in ACF.

Example:

I have a list of parent categories & child categories. Using ACF I create 2 fields say 'Course' & 'Course Option', both category fields, but I want to display Course Option only if a certain value in the Course is selected. However when I go to set the Conditional Logic rule up, Course isn't available as an option for conditional logic.

Is this by design?

Hope you can help.

Matt

**Comment by cubeweb** [comment]
Hi Matt,
No this is not by design. This is a ACF core functionality and should work but I will make a test to see if I get some kind of error.

What version of ACF are you using?

**Comment by seganaUK** [comment]
Thanks for the quick response.

Currently running 4.4.0 of ACF and 2.0.0.7 of ACF Categories.

Matt

**Comment by borysov** [comment]
Conditional Logic support?

**Comment by cubeweb** [comment]
From what I can understand conditional logic works in ACF only when values are static.
In categories field values are dynamically populated so the field does not understand what values to choose. I think this is a ACF core issue and not categories issue. 

I will try to ask Elliot that is the maker of ACF to see if he has more details on this.
