### ISSUE TITLE
Using ACF Categories like ACF Taxonomy?

### ISSUE THREAD

**Issue by ronenschmitz** [cubeweb/acf-categories#5]
Hi there, and thank you for your wonderful and help ACF Plugin and Add-Ons.

I have been using your ACF Taxonomy add-on to show up certain custom fields, depending on which category a post belongs to. This works fine, the assigned categories are written back into the built-in categories. 
But as I have lots different parent categories that I use for different task, and they all show up using this method, my client gets confused. I'd like to show him only the relevant categories of a parent at this place.
So today I've discovered your ACF Categories Add-on and thought, well, this will solve my problem, as I can exclude certain parent or show only certain childs of a parent. 
From the post admin side it looks good, but it won't write back the chosen category back to the built-in categories, like ACF Taxonomy did.
Also, there isn't this "Load & Save Terms to Post" option like with ACF Taxonomy (Load value based on the post's terms and update the post's terms on save).

Would it be possible to implement that in ACF Categories? 
Or is there any other way solving this?

Thank you in advance. Your help would very much be appreciated. 
Ronen

**Comment by cubeweb** [comment]
Hi and thank you for your kind words.
I guess what you are saying is if by choosing one category from the plugin it updates the post's category. I am afraid no for now, but since is a request by others too, I will try to implement it and make a beta version so you can test it.

**Comment by ronenschmitz** [comment]
Hi there,

thanks for the reply. That’d be awesome, and I am ready to beta-test it. Looking very much forward to it.
Well maybe you can get some hints by the original ACF Plugin, which has this implemented for Taxonomies, but as said, it shows all Category hierarchie, and there is no way to include and/or exclude certain parents/IDs.

Also, I have actually gone premium with ACF, so I now have the Advanced Custom Fields Pro Plugin installed. But your Addon ACF Category doesn’t seem to work with it, as Category doesn’t shop up as a field type option…
If you’d like, I could send you the plugin in order to implement it for that as well.
I gather, a lot of people use the Pro version, and would like that, too. ;-)

Regards, and thanks so much in advance.
Ronen

**Comment by cubeweb** [comment]
Hi @ronenschmitz the beta is out.
I have added Update Post Categories option that if is true updates post categories too.
Please test it and send me feedback.

For the ACF 5 I haven't read the documentation yet, so I am not sure when it will be ready.

Thanks

**Comment by cubeweb** [comment]
Hi @ronenschmitz you can help on testing the new version that adds support for ACF v5 here in the development branch https://github.com/cubeweb/acf-categories/tree/develop and report any bugs.

Thanks
