### ISSUE TITLE
Update Post Categories Feedback

### ISSUE THREAD

**Issue by claytoncollie** [cubeweb/acf-categories#6]
First off, thank you so much for responding so quickly and adding this functionality into the plugin.  It is exactly what I needed for my project.

The 2.0.0.8 update works fine when there is a single custom field that controls the categories.  I am using 3 at the same time so that that I can use the Include field to show and hide certain categories in the edit post view. 

When there is only one custom field controlling the category, it updates the post category perfectly.  When there are three custom fields, only the last category is updated.

I know I can do a multi select field, but I want them separated out for the novice computer user to enter the information on a gravity form entry.

Thank you in advance for your help.

![gravity forms with 3 category entries](https://cloud.githubusercontent.com/assets/4236538/7319573/27adf40e-ea5c-11e4-8225-9cb1bec3fce5.png)
![edit single post](https://cloud.githubusercontent.com/assets/4236538/7319572/27ad7b64-ea5c-11e4-9ca6-b1e5283f69ab.png)
![single custom field with include post slugs](https://cloud.githubusercontent.com/assets/4236538/7319575/27afcdf6-ea5c-11e4-9ae6-39758e3ed226.png)
![custom fields](https://cloud.githubusercontent.com/assets/4236538/7319574/27ae288e-ea5c-11e4-82da-e62b8a841c75.png)

**Comment by cubeweb** [comment]
I don't know if we can do much about that. Because when you have 3 fields each one of them overrides the value in the database, so I am sure if this can be fixed.

**Comment by claytoncollie** [comment]
the gravity form assigns all 3 just fine.

**Comment by cubeweb** [comment]
The gravity form is a completely different api then ACF.I will search but I don’t promise anything.
