### ISSUE TITLE
This field in repeater (Update Post Categories)

### ISSUE THREAD

**Issue by borysov** [cubeweb/acf-categories#8]
This field in repeater when option "Update Post Categories" only save first selected category. How save other (multi) from repeater field?

**Comment by cubeweb** [comment]
Yew I know this issue but I am not sure yet how to solve it.

**Comment by borysov** [comment]
Its very important. How I can halp you?

**Comment by Amstramgram** [comment]
I need this too.
In repeater i set select categorie (single value) but only the first row is saved.

**Comment by cubeweb** [comment]
the post can have only on set of categories. in a repeater field you actually update post categories many times inside a loop. so it is logical to take only one update.

**Comment by Amstramgram** [comment]
![capture d ecran 2015-10-21 a 16 47 52](https://cloud.githubusercontent.com/assets/6685969/10640103/877fb242-7813-11e5-90ab-3a6d8e0102bf.png)
With picture it's easier. I have this repeater with one select by row but only the last row is saved.

**Comment by cubeweb** [comment]
this is exactly what I am saying

**Comment by Amstramgram** [comment]
ok sorry.

**Comment by cubeweb** [comment]
I will try to contact Elliot from ACF if he has a solution on this....

**Comment by Amstramgram** [comment]
I do this when i save my post. I don't know if it's help you.

```// - Update custom categories
	$repeater_POST = $_POST['fields']['field_5616869d28c90'];
	$taxonomy = 'taxonomy_colors';
	if( $repeater_POST ){
		unset($repeater_POST['acfcloneindex']);
		$values = array();
		foreach ($repeater_POST as $row) {
			$id = (int)$row['field_561686ae28c91'];
			array_push($values, $id);
		}
		wp_set_post_terms( $post_id, $values, $taxonomy );
	}```
